name: Fly Deploy
on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

defaults:
  run:
    working-directory: api/

jobs:
  deploy:
    name: 🚀 Deploy
    runs-on: ubuntu-latest
    if: ${{ (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/staging') && github.event_name == 'push' }}

    steps:
      - name: 🛑 Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0

      - name: ⬇️ Checkout repo
        uses: actions/checkout@v3

      - name: 👀 Read app name
        uses: SebRollen/toml-action@v1.0.2
        id: app_name
        with:
          file: "api/fly.toml"
          field: "app"

      - name: ☁️ Deploy to production
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
